language: php
dist: trusty
sudo: false

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

before_install:
  - phpenv config-rm xdebug.ini || true

install:
  - composer install --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit --verbose tests